# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Firstjob from Build pipeline
  - job: SecondJob
    steps:
    - bash: echo SecondJob from Build pipeline
- stage: TestDeploy
  dependsOn: Build
  jobs:
    - job: FirstJob
      steps:
      - bash: echo Firstjob from TestDeploy pipeline
- stage: QADeploy
  dependsOn: Build
  jobs:
    - job: FirstJob
      steps:
      - bash: echo Firstjob from QADeploy pipeline
- stage: ProdDeploy
  dependsOn:
  - TestDeploy
  - QADeploy
  jobs:
    - job: FirstJob
      steps:
      - bash: echo Firstjob from ProdDeploy pipeline
  
  

