# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Firstjob from Build pipeline
  - job: SecondJob
    steps:
    - bash: echo SecondJob from Build pipeline
- stage: TestDeploy
  dependsOn: Build
  jobs:
    - job: FirstJob
      steps:
      - bash: echo Firstjob from TestDeploy pipeline
- stage: QADeploy
  dependson: Build
  jobs:
    - job: FirstJob
      steps:
      - bash: echo Firstjob from QADeploy pipeline
- stage: ProdDeploy
  dependson:
  - TestDeploy
  - QADeploy
  jobs:
    - job: FirstJob
      steps:
      - bash: echo Firstjob from ProdDeploy pipeline
  
  


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
